### ISSUE TITLE
calculating the accuracy can't get the demo's result

### ISSUE THREAD

**Issue by YuChenSSR** [qccontest/QC-Contest-Demo#1]
TypeError                                 Traceback (most recent call last)
Cell In[28], line 1
----&gt; 1 accuracy = res / ref_value
      2 print(accuracy)
TypeError: unsupported operand type(s) for /: 'ElectronicStructureResult' and 'float'

**Comment by qccontest** [comment]
Thanks for point out! This issue is because previous we directly calculate the expectation. Now a new version is updated, should be works!
